services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-broker/config:/mosquitto/config
      - ./mqtt-broker/data:/mosquitto/data
      - ./mqtt-broker/log:/mosquitto/log
  sensors:
    build:
      context: ./sensors
      dockerfile: Dockerfile
    image: sensors
    container_name: sensors-simulator
    restart: unless-stopped
    depends_on:
      - mosquitto
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:sts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
  nodered:
    container_name: node-red
    restart: unless-stopped
    build:
      context: .
      dockerfile: node-red-data/Dockerfile
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    environment:
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUXDB_URL: ${INFLUXDB_URL}
    depends_on:
      - mosquitto
      - influxdb
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: 0
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 5s
      retries: 30

  influxdb-template-importer:
    image: influxdb:2.7
    container_name: influxdb-template-importer
    depends_on:
      - influxdb
    volumes:
      - ./influxdb/templates:/templates:ro
      - ./influxdb/scripts/apply-templates.sh:/apply-templates.sh:ro
    environment:
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    entrypoint: ["/bin/sh", "/apply-templates.sh"]
    restart: "no"


volumes:
  portainer_data:
    name: portainer_data
  node-red-data:
    name: node_red_data


networks:
  default:
    name: portainer_network
